### PR TITLE
Optionally install Java Cryptography Extension (JCE)

### PR DESCRIPTION
**Pull request by boorad**
Optionally install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy files

### CODE REVIEW

**Comment by tylerwalts** [comment]
Thanks, this is a great add.  Could we either get this to work with the other java versions, or just update the Readme and the param documentation to specify that it only works for version 8?

**Comment by boorad** [comment]
added README and version change.  I couldn't find downloads for v6 or v7.

**Comment by tylerwalts** [comment]
Thanks!

**Comment by boorad** [comment]
Sweet.  When does this get into forge.puppetlabs.com ?

**Pull request merged**
